version: "3.7"
services:
  chatapp-backend:
    build:
      context: ./backend
    command: "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app # Mount your local backend directory into the container
    networks:
      - chatapp_network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./backend/init-mongodb.js:/docker-entrypoint-initdb.d/init-mongodb.js
    networks:
      - chatapp_network

networks:
  chatapp_network:
    driver: bridge

volumes:
  mongodb_data:
