version: "3.7"
services:
  lucencia-backend:
    build: .
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mongodb
    networks:
      - lucentia_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./init-mongodb.js:/docker-entrypoint-initdb.d/init-mongodb.js
    networks:
      - lucentia_network

networks:
  lucentia_network:
    driver: bridge

volumes:
  mongodb_data:
